baseurl = "http://gustafholm.com/"
title = "gustafholm.com"

disableHugoGeneratorInject = true
disableLiveReload = true # disable to test lighthouse/axe locally

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 1
    [languages.en.params]
      description = "Thoughs and notes by Gustaf Holm"
      code = "en-US"
      dir = "ltr"

  [languages.sv]
    contentDir = "content/swedish"
    languageName = "Swedish"
    weight = 2
    [languages.sv.params]
      description = "Tankar och antekningar av Gustaf Holm"
      code = "sv-SE"
      dir = "ltr"
