[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.82.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'"
