[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.82.1"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"
