backend:
  name: gitlab
  branch: master
  repo: primalivet/com_gustafholm

site_url: https://gustafholm.com
media_folder: "site/static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "site/content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Expiry date", name: "expirydate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
