backend:
  name: gitlab
  branch: master
  repo: primalivet/com_gustafholm

site_url: https://gustafholm.com
media_folder: "site/static/images/uploads"
public_folder: "/images/uploads"

media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: primalivet
    api_key: 252849228869977

collections:
  - label: "Posts"
    label_singular: "Post"
    name: "posts"
    folder: "site/content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Authors"
    label_singular: "Author"
    name: "authors"
    folder: "site/content/authors"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Bio", name: "body", widget: "markdown" }
