backend:
  name: git-gateway
  branch: master
  repo: primalivet/com_gustafholm

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "layout", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Content", name: "content", widget: "markdown" }
