backend:
  name: git-gateway
  branch: master
 
# site_url: https://gustafholm.com

# media_folder is set to the uploads dir in english content as that makes
# uploads available cross languages and enables hugo page bundle so that we can
# use image resources for scaling etc.
media_folder: "content/english/uploads"

collections:
  - label: "Authors (en)"
    label_singular: "Author (en)"
    name: "authors_en"
    folder: "content/english/authors"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Bio", name: "body", widget: "markdown", required: false }

  - label: "Posts (en)"
    label_singular: "Post (en)"
    name: "posts_en"
    folder: "content/english/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "relation", collection: "authors_en", search_fields: ["title"], value_field: "title", required: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Authors (sv)"
    label_singular: "Author (sv)"
    name: "authors_sv"
    folder: "content/swedish/authors"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Bio", name: "body", widget: "markdown", required: false }

  - label: "Posts (sv)"
    label_singular: "Post (sv)"
    name: "posts_sv"
    folder: "content/swedish/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishdate", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "relation", collection: "authors_sv", search_fields: ["title"], value_field: "title", required: true }
      - { label: "Body", name: "body", widget: "markdown" }

